title: Rosielin Group
email: rosielingroup@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Rosielin Group consists of volunteers in the field of Medicine, Computer Science, Finance and Biology. We as a group want to share correct and optimistic results in Science. The group was started during the Coronavirus pandemic when we saw the overwhelming amount of uncertainty and pessimism. We wanted to bring ongoing research that's meant to give us all a ray of hope to the general public and bring about optimism while not being wrong.
  The group name is a tribute to the great Rosalind Elsie Franklin. Her work is central to almost everything we know about Biology today.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Rosielin # add your name
author-pic: rosielin-01.png
about-author: The Rosielin Group consists of volunteers in the field of Medicine, Computer Science, Finance and Biology. We as a group want to share correct and optimistic results in Science. The group was started during the Coronavirus pandemic when we saw the overwhelming amount of uncertainty and pessimism. We wanted to bring ongoing research that's meant to give us all a ray of hope to the general public and bring about optimism while not being wrong.
  The group name is a tribute to the great Rosalind Elsie Franklin. Her work is central to almost everything we know about Biology today.


# Contact links
email: rosielingroup@gmail.com # Add your Email address
phone: +91 7709769564 # Add your Phone number
website: rosielin-group.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: rosielin-group # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: rosielin # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
